#prefix used to show metrics in AppDynamics
#metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Azure|"
metricPrefix: "Custom Metrics|Azure|"

accounts:
  - displayName: "Azure Storage Monitor"
    credentials:
         client: "${CLIENT_ID}"
         tenant: "${TENANT_ID}"
         secret: "${CLIENT_SECRET}"
         subscriptionId: "${SUBSCRIPTION_ID}"

    services:
       - resourceGroups: ["my-rg-tf"]  # Please put the required resourceGroups only
         serviceName: "Storage account"
         regions: ["eastus"]
         serviceInstances: ["diag.*"]

# aggregationType ==> "None", "Average", "Minimum", "Maximum", "Total", "Count" refer: https://docs.microsoft.com/en-us/azure/azure-monitor/app/metrics-explorer
#    targets:
#       - displayName: "Az Containers"
#         resource: "/resourceGroups/<MY-RESOURCE-GROUP>/providers/Microsoft.Compute/virtualMachines/<MY-RESOURCE>/providers/microsoft.insights/metrics"
#         resourceGroups: ["my-rg"]
#         serviceInstances: ["my-vm"]
#         metrics:
#            - attr: "Network In Total"
#              aggregationType: "count"
#            - attr: "Network Out Total"
#              aggregationType: "count"
#            - attr: "Disk Write Bytes"
#              aggregationType: "count"
#            - attr: "Disk Read Operations/Sec"
#              aggregationType: "count"
#            - attr: "Disk Write Operations/Sec"
#              aggregationType: "count"


proxyConfig:
  host:
  port:
  username:
  password:

metricsTimeRange:
  startTimeInMinsBeforeNow: 50
  endTimeInMinsBeforeNow: 0

concurrencyConfig:
  noOfResourceGroupThreads: 3
  noOfServiceCollectorThreads: 3
  threadTimeout: 30  #Thread timeout in seconds

connection:
  sslCertCheckEnabled: false
  socketTimeout: 10000
  connectTimeout: 10000

#By default we support upto 5 accounts, and 1 thread is required per account.
numberOfThreads: 5
filterStats: false # flag to use metrics.xml.

controllerInfo:
    controllerHost: "localhost"
    controllerPort: 8090
    account: "customer1"
    username: "admin"
    password: "admin"
    encryptedPassword: ""
    encryptionKey: ""
    controllerSslEnabled: false
    enableOrchestration: false
    uniqueHostId: ""
    accountAccessKey: "c71836c2-5128-4545-9ef5-c6dfc6a69952"
    machinePath: ""
    simEnabled: true
    applicationName: ""
    tierName: ""
    nodeName: ""

#Encryption key for your controllerInfo password
encryptionKey: ""
#================================= Example configurations below =================================
#  - displayName: "AzureAccount Storage"
#    resourceGroups: ["test-ext.*"]
#    serviceName: "Storage account"
#    regions: ["East US"]
#    serviceInstances: [".*"]

#  - displayName: "AzureAccount Sql server"
#    resourceGroups: [".*"]
#    serviceName: "SQL server"
#    regions: ["australia.*"]
#    serviceInstances: [".*"]