#prefix used to show metrics in AppDynamics
metricPrefix: "Server|Component:<TIER_ID>|Custom Metrics|Azure|"
#metricPrefix: "Custom Metrics|Azure|"

accounts:
#https://docs.microsoft.com/en-us/azure/virtual-machines/linux/metrics-vm-usage-rest
  - displayName: "AzureAccount VM"
    resourceGroups: [".*"]  # Please put the concerned resourceGroups only
    service: "Virtual machine"
    regions: [".*"]
    serviceInstances: [".*"]
    credentials:
         client: ""
         tenant: ""
         secret: ""
         subscriptionId: ""

    targets:
       - displayName: "VM Target"
         resource: "/resourceGroups/my-rg/providers/Microsoft.Compute/virtualMachines/myvm/providers/microsoft.insights/metrics"
         metrics:
            - attr: "Network Out Total"
            - attr: "Disk Write Bytes"
            - attr: "Disk Read Operations/Sec"
            - attr: "Disk Write Operations/Sec"
         apiVersion: "2019-07-01"
         timeSpan: "10" #in minutes https://docs.microsoft.com/en-us/windows/win32/taskschd/repetitionpattern-interval

#  - displayName: "AzureAccount Storage"
#    resourceGroups: ["test-ext.*"]
#    service: "Storage account"
#    regions: ["East US"]
#    serviceInstances: [".*"]
#    credentials:
#         client: ""
#         tenant: ""
#         secret: ""
#         subscriptionId: ""
#
#  - displayName: "AzureAccount Container"
#    resourceGroups: [".*"]
#    service: "Container instances"
#    regions: [".*"]
#    serviceInstances: [".*"]
#    credentials:
#         client: ""
#         tenant: ""
#         secret: ""
#         subscriptionId: ""

#  - displayName: "AzureAccount Sql server"
#    resourceGroups: [".*"]
#    service: "SQL server"
#    regions: ["australia.*"]
#    serviceInstances: [".*"]
#    credentials:
#         client: ""
#         tenant: ""
#         secret: ""
#         subscriptionId: ""

#Provide Encryption key for Encrypted password.
credentialsDecryptionConfig:
  enableDecryption: "false"
  encryptionKey:

proxyConfig:
  host:
  port:
  username:
  password:


filterStats: false

metricsTimeRange:
  startTimeInMinsBeforeNow: 50
  endTimeInMinsBeforeNow: 0

concurrencyConfig:
  noOfResourceGroupThreads: 3
  noOfMetricsCollectorThreads: 3
  threadTimeout: 30  #Thread timeout in seconds

#TODO: decide an equation for threads being used
numberOfThreads: 30